URL_SITE = "https://www.iada.com.br"
NME_PROJ = "AgroTom"
RODA_PE_PDF = "#{NME_PROJ} - Emitido em - "
AVATAR_URL_DEFAULT = "../../#{Rails.root}/app/javascript/stylesheets/images/barcode.png"
URL_LOGO_SITE ="../../#{Rails.root}/app/assets/logo.png"
URL_IMAGE_LOGUIN="images/agronomicas-sementes.jpg"
