 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/files/files", type: :request do
  # Files::File. As you add validations to Files::File, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Files::File.create! valid_attributes
      get files_files_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      file = Files::File.create! valid_attributes
      get files_file_url(files_file)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_files_file_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      file = Files::File.create! valid_attributes
      get edit_files_file_url(files_file)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Files::File" do
        expect {
          post files_files_url, params: { files_file: valid_attributes }
        }.to change(Files::File, :count).by(1)
      end

      it "redirects to the created files_file" do
        post files_files_url, params: { files_file: valid_attributes }
        expect(response).to redirect_to(files_file_url(Files::File.lasts_file))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Files::File" do
        expect {
          post files_files_url, params: { files_file: invalid_attributes }
        }.to change(Files::File, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post files_files_url, params: { files_file: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested files_file" do
        file = Files::File.create! valid_attributes
        patch files_file_url(files_file), params: { files_file: new_attributes }
        file.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the files_file" do
        file = Files::File.create! valid_attributes
        patch files_file_url(files_file), params: { files_file: new_attributes }
        file.reload
        expect(response).to redirect_to(files_file_url(file))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        file = Files::File.create! valid_attributes
        patch files_file_url(files_file), params: { files_file: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested files_file" do
      file = Files::File.create! valid_attributes
      expect {
        delete files_file_url(files_file)
      }.to change(Files::File, :count).by(-1)
    end

    it "redirects to the files_files list" do
      file = Files::File.create! valid_attributes
      delete files_file_url(files_file)
      expect(response).to redirect_to(files_files_url)
    end
  end
end
